#!/bin/bash

# NOTE: to use this file, install bud first: https://github.com/dohsimpson/bud
# then run: `bud help`

help() {
  echo "TaskTrove Dev Script"
  echo ""
  echo "Commands:"
  echo "  dev                 Start dev server"
  echo "  run <script>        Run pnpm script"
  echo "  docker-build [tag]  Build Docker image"
}

dev() {
  pnpm dev
}

run() {
  if [ -z "$1" ]; then
    echo "Usage: bud run <script>"
    return 1
  fi
  pnpm run "$1"
}

docker-build() {
  docker build -t "${1:-dohsimpson/tasktrove:latest}" .
}

docker-run() {
  docker run -it --rm -p 3000:3000 -v ./data:/app/data dohsimpson/tasktrove
}

# Show help when no arguments are provided
if [ $# -eq 0 ]; then
  help
fi
