packages:
  - "apps/*"
  - "packages/*"
  - "modules.pro/apps/*"
  - "modules.pro/packages/*"

catalog:
  # Build tools
  turbo: "^2.5.6"
  typescript: "^5.9.2"
  prettier: "^3.6.2"

  # Core React ecosystem
  react: "^19.1.1"
  react-dom: "^19.1.1"
  next: "15.2.4"
  "@hookform/resolvers": "^5.2.2"
  "react-hook-form": "^7.63.0"
  "react-i18next": "^15.7.3"
  "react-day-picker": "^9.11.0"
  "react-resizable-panels": "^3.0.6"

  # TanStack Query
  "@tanstack/query-core": "^5.90.1"
  "@tanstack/react-query": "^5.90.1"

  # UI and styling
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "tailwind-merge": "^3.3.1"
  "lucide-react": "^0.544.0"
  "@icons-pack/react-simple-icons": "^13.7.0"
  "motion": "^12.23.18"

  # Utilities and core libraries
  "@uidotdev/usehooks": "^2.4.1"
  "accept-language": "^3.0.20"
  "archiver": "^7.0.1"
  "async-mutex": "^0.5.0"
  "cmdk": "^1.1.1"
  "embla-carousel-react": "^8.6.0"
  "input-otp": "^1.4.2"
  "linkify-react": "^4.3.2"
  "linkifyjs": "^4.3.2"
  "next-logger": "^5.0.1"
  "next-themes": "^0.4.6"
  "node-cron": "^4.2.1"
  "pino": "^9.11.0"
  "recharts": "^3.2.1"
  "slugify": "^1.6.6"
  "sonner": "^2.0.7"
  "uuid": "^13.0.0"
  "vaul": "^1.1.2"
  "zod": "^4.1.11"

  # Internationalization
  "i18next": "^25.5.2"
  "i18next-browser-languagedetector": "^8.2.0"
  "i18next-resources-to-backend": "^1.2.1"

  # State management
  "jotai": "^2.14.0"
  "jotai-history": "^0.4.3"
  "jotai-tanstack-query": "^0.11.0"

  # Radix UI components
  "@radix-ui/react-accordion": "^1.2.12"
  "@radix-ui/react-alert-dialog": "^1.1.15"
  "@radix-ui/react-aspect-ratio": "^1.1.7"
  "@radix-ui/react-avatar": "^1.1.10"
  "@radix-ui/react-checkbox": "^1.3.3"
  "@radix-ui/react-collapsible": "^1.1.12"
  "@radix-ui/react-context-menu": "^2.2.16"
  "@radix-ui/react-dialog": "^1.1.15"
  "@radix-ui/react-dropdown-menu": "^2.1.16"
  "@radix-ui/react-hover-card": "^1.1.15"
  "@radix-ui/react-label": "^2.1.7"
  "@radix-ui/react-menubar": "^1.1.16"
  "@radix-ui/react-navigation-menu": "^1.2.14"
  "@radix-ui/react-popover": "^1.1.15"
  "@radix-ui/react-progress": "^1.1.7"
  "@radix-ui/react-radio-group": "^1.3.8"
  "@radix-ui/react-scroll-area": "^1.2.10"
  "@radix-ui/react-select": "^2.2.6"
  "@radix-ui/react-separator": "^1.1.7"
  "@radix-ui/react-slider": "^1.3.6"
  "@radix-ui/react-slot": "^1.2.3"
  "@radix-ui/react-switch": "^1.2.6"
  "@radix-ui/react-tabs": "^1.1.13"
  "@radix-ui/react-toast": "^1.2.15"
  "@radix-ui/react-toggle": "^1.1.10"
  "@radix-ui/react-toggle-group": "^1.1.11"
  "@radix-ui/react-tooltip": "^1.2.8"
  "@radix-ui/react-visually-hidden": "^1.2.3"

  # ESLint ecosystem
  eslint: "^9.31.0"
  "@eslint/js": "^9.34.0"
  "@typescript-eslint/eslint-plugin": "^8.38.0"
  "@typescript-eslint/parser": "^8.38.0"
  "typescript-eslint": "^8.40.0"
  "eslint-config-prettier": "^10.1.1"
  "eslint-plugin-react": "^7.37.5"
  "eslint-plugin-react-hooks": "^5.2.0"
  "eslint-plugin-turbo": "^2.5.0"
  "eslint-plugin-only-warn": "^1.1.0"
  "@next/eslint-plugin-next": "^15.5.0"
  "eslint-config-next": "^15.3.5"
  globals: "^16.3.0"

  # Type definitions
  "@types/node": "^22.15.3"
  "@types/react": "^19.1.13"
  "@types/react-dom": "^19.1.1"
  "@types/archiver": "^6.0.3"
  "@types/node-cron": "^3.0.11"
  "@types/uuid": "^10.0.0"

  # Testing
  vitest: "^3.2.4"
  "@vitest/coverage-v8": "^3.2.4"
  "@testing-library/jest-dom": "^6.6.3"
  "@testing-library/react": "^16.3.0"
  "@testing-library/user-event": "^14.6.1"
  "happy-dom": "^18.0.1"
  jsdom: "^26.1.0"

  # Build and bundling
  "@next/bundle-analyzer": "^15.4.6"
  postcss: "^8.5.0"
  tailwindcss: "^4.1.11"
  "@tailwindcss/postcss": "^4.1.11"

  # Development tools
  "@changesets/cli": "^2.29.7"
  "@changesets/get-github-info": "^0.6.0"
  husky: "^9.1.7"
  "lint-staged": "^16.2.0"
  "i18next-parser": "^9.3.0"
  "jotai-devtools": "^0.13.0"
  "pino-pretty": "^13.1.1"
  "animate.css": "^4.1.1"
  "tw-animate-css": "^1.3.8"
  "@typescript/native-preview": "7.0.0-dev.20250723.1"
  "@tanstack/react-query-devtools": "5.90.1"

  # Drag and drop
  "@atlaskit/pragmatic-drag-and-drop": "^1.7.7"
  "@atlaskit/pragmatic-drag-and-drop-hitbox": "^1.1.0"
  "@atlaskit/pragmatic-drag-and-drop-react-drop-indicator": "^3.2.7"
