packages:
  - apps/*
  - packages/*
  - modules.pro/apps/*
  - modules.pro/packages/*

catalog:
  "@atlaskit/pragmatic-drag-and-drop-auto-scroll": ^2.1.2
  "@atlaskit/pragmatic-drag-and-drop-hitbox": ^1.1.0
  "@atlaskit/pragmatic-drag-and-drop-react-drop-indicator": ^3.2.7
  "@atlaskit/pragmatic-drag-and-drop": 1.7.7
  "@capacitor/android": ^7.4.4
  "@capacitor/app-launcher": ^7.0.2
  "@capacitor/app": ^7.1.0
  "@capacitor/cli": ^7.4.4
  "@capacitor/core": ^7.4.4
  "@capacitor/haptics": ^7.0.2
  "@capacitor/ios": ^7.4.4
  "@capacitor/local-notifications": ^7.0.3
  "@capacitor/preferences": ^7.0.2
  "@capacitor/splash-screen": ^7.0.4
  "@capawesome-team/capacitor-android-battery-optimization": ^7.0.0
  "@capawesome/capacitor-badge": ^7.0.1
  "@capgo/capacitor-updater": ^8.41.5
  "@changesets/cli": ^2.29.7
  "@changesets/get-github-info": ^0.6.0
  "@eslint/js": ^9.34.0
  "@hookform/resolvers": ^5.2.2
  "@icons-pack/react-simple-icons": ^13.7.0
  "@ionic/core": ^8.7.9
  "@ionic/react-router": ^8.7.9
  "@ionic/react": ^8.7.9
  "@khmyznikov/pwa-install": ^0.5.8
  "@next/bundle-analyzer": ^16.0.10
  "@next/eslint-plugin-next": ^16.0.10
  "@radix-ui/react-accordion": ^1.2.12
  "@radix-ui/react-alert-dialog": ^1.1.15
  "@radix-ui/react-aspect-ratio": ^1.1.7
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.3
  "@radix-ui/react-collapsible": ^1.1.12
  "@radix-ui/react-context-menu": ^2.2.16
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-hover-card": ^1.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-menubar": ^1.1.16
  "@radix-ui/react-navigation-menu": ^1.2.14
  "@radix-ui/react-popover": ^1.1.15
  "@radix-ui/react-progress": ^1.1.7
  "@radix-ui/react-radio-group": ^1.3.8
  "@radix-ui/react-scroll-area": ^1.2.10
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slider": ^1.3.6
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.2.6
  "@radix-ui/react-tabs": ^1.1.13
  "@radix-ui/react-toast": ^1.2.15
  "@radix-ui/react-toggle-group": ^1.1.11
  "@radix-ui/react-toggle": ^1.1.10
  "@radix-ui/react-tooltip": ^1.2.8
  "@radix-ui/react-visually-hidden": ^1.2.3
  "@react-spring/web": ^10.0.3
  "@tailwindcss/postcss": ^4.1.11
  "@tailwindcss/typography": ^0.5.16
  "@tanstack/query-core": ^5.90.1
  "@tanstack/react-query-devtools": 5.90.1
  "@tanstack/react-query": ^5.90.1
  "@tanstack/react-table": 8.21.3
  "@tanstack/react-virtual": ^3.13.12
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/archiver": ^6.0.3
  "@types/bcryptjs": ^2.4.6
  "@types/color": ^4.1.0
  "@types/node-cron": ^3.0.11
  "@types/node": ^22.15.3
  "@types/papaparse": ^5.3.16
  "@types/react-dom": ^19.2.3
  "@types/react": ^19.2.7
  "@types/uuid": ^10.0.0
  "@typescript-eslint/eslint-plugin": ^8.38.0
  "@typescript-eslint/parser": ^8.38.0
  "@typescript/native-preview": 7.0.0-dev.20250723.1
  "@uidotdev/usehooks": ^2.4.1
  "@use-gesture/react": ^10.3.1
  "@vitest/coverage-v8": ^3.2.4
  accept-language: ^3.0.20
  animate.css: ^4.1.1
  archiver: ^7.0.1
  async-mutex: ^0.5.0
  auto-scroll-while-dragging: ^1.0.1
  bcryptjs: ^2.4.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  color: ^4.2.3
  commander: ^14.0.1
  concurrently: ^9.1.2
  cron-parser: ^4.9.0
  date-fns: ^4.1.0
  electron-builder: ^26.0.12
  electron-is-dev: ^3.0.1
  electron: ^38.2.0
  embla-carousel-react: ^8.6.0
  esbuild: ^0.25.11
  eslint-config-next: ^16.0.10
  eslint-config-prettier: ^10.1.1
  eslint-config-turbo: ^2.5.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-turbo: ^2.5.0
  eslint: ^9.31.0
  globals: ^16.3.0
  happy-dom: ^18.0.1
  husky: ^9.1.7
  i18next-browser-languagedetector: ^8.2.0
  i18next-cli: ^1.19.3
  i18next-parser: ^9.3.0
  i18next-resources-to-backend: ^1.2.1
  i18next: ^25.5.2
  input-otp: ^1.4.2
  javascript-obfuscator: ^4.1.1
  jotai-devtools: ^0.13.0
  jotai-history: ^0.4.3
  jotai-tanstack-query: ^0.11.0
  jotai: ^2.14.0
  jsdom: ^26.1.0
  konsta: ^5.0.4
  linkify-react: ^4.3.2
  linkifyjs: ^4.3.2
  lint-staged: ^16.2.0
  lucide-react: ^0.544.0
  mobile-drag-drop: 3.0.0-rc.0
  motion: ^12.23.25
  next-logger: ^5.0.1
  next-themes: ^0.4.6
  next: ^16.0.10
  node-cron: ^4.2.1
  papaparse: ^5.5.3
  pino-pretty: ^13.1.1
  pino: ^9.11.0
  postcss-import-ext-glob: ^2.1.1
  postcss-import: ^16.1.1
  postcss: ^8.5.0
  prettier: ^3.6.2
  radix-ui: ^1.1.3
  react-day-picker: ^9.11.0
  react-dom: ^19.2.3
  react-hook-form: ^7.63.0
  react-i18next: ^15.7.3
  react-markdown: ^10.1.0
  react-resizable-panels: ^3.0.6
  react: ^19.2.3
  recharts: ^3.2.1
  remark-gfm: ^4.0.1
  rrule: ^2.8.1
  slugify: ^1.6.6
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tsx: ^4.20.6
  turbo: ^2.5.6
  tw-animate-css: ^1.3.8
  typescript-eslint: ^8.40.0
  typescript: ^5.9.2
  uuid: ^13.0.0
  vaul: ^1.1.2
  vitepress: ^1.6.4
  vitest: ^3.2.4
  wait-on: ^8.0.1
  webpack-obfuscator: ^3.5.1
  zod-openapi: ^5.4.2
  zod: ^4.1.11

catalogMode: strict


patchedDependencies:
  "@atlaskit/pragmatic-drag-and-drop-react-drop-indicator": apps/web/patches/@atlaskit__pragmatic-drag-and-drop-react-drop-indicator.patch
